<?php include "../../model/model.php"; ?>
<?php
$report_generater_name = "";
$role = $_SESSION['role'];
if($role=="Admin")
{
  $report_generater_name = "Admin";
}
if($role=="Booker")
{
  $booker_id = $_SESSION['booker_id'];
  $booker_name = mysql_fetch_assoc(mysql_query("select first_name, last_name from emp_master where emp_id='$booker_id'"));
  $report_generater_name = $booker_name['first_name']." ".$booker_name['last_name'];
}  

$_SESSION['generated_by'] = $report_generater_name;





define('FPDF_FONTPATH','../../classes/fpdf/font/');
//require('../../classes/fpdf/fpdf.php');
require('../../classes/mc_table.php');


$pdf=new PDF_MC_Table();
$pdf->AddPage();

$pdf->SetFont('Arial','',12);
$pdf->SetXY(0,0);
$pdf->Cell( 100, 12, $pdf->Image($report_logo_url,0,5,200,25), 0, 0, 'C', false );

$ypos = $pdf->GetY();
$pdf->SetXY(100,$ypos);
//$pdf->Cell( 100, 10, "Generated by : ".$report_generater_name,0, 0, 'R' );

$pdf->ln();
$pdf->ln();
$pdf->ln();

$bus_id = $_GET['bus_id'];
$tour_id = $_GET['tour_id'];
$tour_group_id = $_GET['tour_group_id'];

$sq_tour_name = mysql_query("select tour_name from tour_master where tour_id='$tour_id'");
$row_tour_name = mysql_fetch_assoc($sq_tour_name);
$tour_name = $row_tour_name['tour_name'];

$sq_tour_group_name = mysql_query("select from_date,to_date from tour_groups where group_id='$tour_group_id'");
$row_tour_group_name = mysql_fetch_assoc($sq_tour_group_name);
$tour_group_from = date("d-m-Y", strtotime($row_tour_group_name['from_date']));
$tour_group_to = date("d-m-Y", strtotime($row_tour_group_name['to_date']));

$sq_bus_det = mysql_fetch_assoc(mysql_query("select bus_name from bus_master where bus_id='$bus_id'"));

$y_postion = $pdf->getY();
$pdf->SetXY(10,$y_postion);
$pdf->Cell( 30, 7, 'Tour Name :', 1, 1, 'L', false );   
$pdf->SetXY(40,$y_postion);
$pdf->Cell( 95, 7, $tour_name, 1, 1, 'L', false );   
$y_postion = $pdf->getY();
$pdf->SetXY(10,$y_postion);
$pdf->Cell( 30, 7, 'Tour Group :', 1, 1, 'L', false );   
$pdf->SetXY(40,$y_postion);
$pdf->Cell( 95, 7, $tour_group_from." to ".$tour_group_to, 1, 1, 'L', false );   
$y_postion = $pdf->getY();
$pdf->SetXY(10,$y_postion);
$pdf->Cell( 30, 7, 'Bus Type :', 1, 1, 'L', false );   
$pdf->SetXY(40,$y_postion);
$pdf->Cell( 95, 7, $sq_bus_det['bus_name'], 1, 1, 'L', false );  

$pdf->ln(); 

$pdf->SetFont('Arial','B',14);
$pdf->MultiCell( 125, 15, 'Bus Seating Arrangment Report', 1, 'C' );



$pdf->SetFont('Arial','',12);
$pdf->SetWidths(array(20,35,70));


$pdf->Row(array('Sr. No', 'Seat Number', 'Traveler Name'));

$header_array = array('Sr. No', 'Seat Number', 'Traveler Name');
$_SESSION['header_array'] = $header_array;


$pdf->SetFont('Arial','',10);



$role = $_SESSION['role'];



$count = 0;

$sq_bus_arr_det = mysql_query("select * from bus_seat_arrangment_master where tour_id='$tour_id' and tour_group_id='$tour_group_id' and bus_id='$bus_id' ");
while($row_bus_arr_det = mysql_fetch_assoc($sq_bus_arr_det))
{
	$count++;

	$sq_travelr_det = mysql_fetch_assoc(mysql_query("select * from travelers_details where traveler_id='$row_bus_arr_det[traveler_id]'"));

	$pdf->Row(array($count, $row_bus_arr_det['seat_no'], $sq_travelr_det['m_honorific']." ".$sq_travelr_det['first_name']." ".$sq_travelr_det['middle_name']." ".$sq_travelr_det['last_name']));

}


unset($_SESSION['header_array']);
$pdf->Output();

?>